### PR TITLE
Better logging. Use logrus for logging. Add log command

### PR DESCRIPTION
**Pull request by vansante**
@SvenWiltink Reapplied my logging changes to a fresh fork ;)

### CODE REVIEW

**Comment by SvenWiltink** [comment]
Please Her Royal Linterness :+1:

**Comment by SvenWiltink** [comment]
@vansante What is the advantage of using logrus?

**Comment by vansante** [comment]
You can have loglevels, set output formatters, add hooks, etc.
See https://github.com/sirupsen/logrus

**Comment by vansante** [comment]
@SvenWiltink I declare it Done (tm) :)

**Pull request merged**
