### PR TITLE
Add playlist item page listing to add more items at once

### PR DESCRIPTION
**Pull request by vansante**

### CODE REVIEW

**Comment by vansante** [comment]
@svenwiltink This fixes some bugs & adds support for large playlists

**Comment by svenwiltink** [comment]
tested and ready to be merged?

**Comment by vansante** [comment]
Its been running on plebski for a while

**Comment by vansante** [comment]
But actually, I just found a bug :p

**Comment by vansante** [comment]
@svenwiltink I declare it stable(ish) :D

**Pull request merged**
